config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "/signup", to: "users#new"
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/activation", to: "payments#activation"
    get "/showing_movie", to: "specific_movies#showing_movie"
    get "/comming_movie", to: "specific_movies#comming_movie"
    resources :payments
    resources :searchs, only: :index
    resources :order_historys
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(show destroy index)
    resources :payment_activations, only: :edit
    resources :tickets
    resources :users
    resources :rates, only: :create
    resources :categories, only: :show
    resources :favorites, only: %i(index create destroy)
    resources :movies, only: %i(show) do
      resources :shows
    end

    resources :charts, only: [] do
      collection do
        get "top_movies_seller"
        get "top_movies_booking"
        get "revenue_by_day"
      end
    end

    namespace :admin do
      root "static_pages#home"
      get "/home", to: "static_pages#home"
      resources :movies
      resources :categories
      resources :show_times
      resources :cinemas
      resources :payments
      resources :users, only: %i(index show update)
    end
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/show_time.rb
class ShowTime < ApplicationRecord
  SHOW_ATTR = %i(price start_time movie_id room_id end_time).freeze

  has_many :tickets, dependent: :restrict_with_exception
  belongs_to :movie
  belongs_to :room

  before_validation :update_end_time
  validates :start_time, :price, :movie_id, :room_id, presence: true
  validate :valid_overlap_showtime

  delegate :cinema_name, to: :room
  delegate :title, to: :movie, prefix: :movie
  delegate :name, to: :room, prefix: :room

  scope :filter_date, lambda{|movie_id, date|
    where "(movie_id = ? AND start_time BETWEEN ? AND ? )",
          movie_id,
          date.to_datetime.to_date == DateTime.now.to_date ? DateTime.now : date.to_datetime.beginning_of_day,
          date.to_datetime.end_of_day
  }
  scope :date_available, (lambda do
    where("start_time < AND end_time > ?", DateTime.now.end_of_day, Time.now)
  end)
  scope :not_out_of_date, ->{ where "(end_time > ? )", Time.now.beginning_of_day }
  scope :incre_order, ->{order id: :asc}
  scope :find_room, ->(room_id){where "room_id = ?", room_id}
  scope :by_month, ->(month){where("MONTH(start_time) = ?", month)}
  scope :overlap, lambda {|start_time, end_time|
                    where "((start_time <= ? AND end_time > ?)
                            OR (end_time >= ? AND start_time < ?)
                            OR (start_time >= ? AND end_time <= ?)
                            )",
                          end_time + 5.minutes, end_time + 5.minutes,
                          start_time - 5.minutes, start_time - 5.minutes,
                          start_time - 5.minutes, end_time + 5.minutes
                  }

  ransacker :start_time, type: :date do
    Arel.sql("date(start_time)")
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "end_time", "id", "movie_id", "price", "room_id", "start_time", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["movie", "room", "tickets"]
  end

  def valid_overlap_showtime
    return unless start_time
    return if ShowTime.find_room(room_id).overlap(start_time, end_time).blank?

    errors.add(:start_time, message: I18n.t("time_overlap"))
  end

  def valid_start_time
    return if start_time > (Time.now + 1.days)

    errors.add(:start_time, message: I18n.t("time_less_than"))
  end

  def self.ransackable_scopes _auth_object = nil
    %i(filter_date)
  end

  def update_end_time
    self.end_time = start_time + movie.duration_min.minutes if start_time
  end
end

app/controllers/admin/show_times_controller.rb
class Admin::ShowTimesController < AdminController
  before_action :find_show, only: %i(edit update destroy)

  def index
    @search = ShowTime.not_out_of_date.ransack params[:q]
    @pagy, @shows = pagy @search.result,
                          items: Settings.model.limited
  end

  def new
    @show = ShowTime.new
  end

  def create
    @show = ShowTime.new show_params
    if @show.save
      flash[:success] = t ".show_create"
      redirect_to admin_show_times_path
    else
      flash[:danger] = t ".show_create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if @show.tickets.any?
      flash[:danger] = t "ticket_present"
      render :edit
    elsif @show.update show_params
      flash[:success] = t ".show_update"
      redirect_to admin_show_times_path
    else
      flash[:danger] = t ".show_update_failed"
      render :edit
    end
  end

  def destroy
    if @show.tickets.any?
      flash[:danger] = t "ticket_present"
      return redirect_to admin_show_times_path
    elsif @show.destroy
      flash[:success] = t ".show_delete"
    else
      flash[:danger] = t ".show_delete_failed"
    end
    redirect_to admin_show_times_path
  end

  private
  def show_params
    params.require(:show_time).permit ShowTime::SHOW_ATTR
  end

  def find_show
    @show = ShowTime.find_by id: params[:id]
    return if @show

    flash[:danger] = t "not_found"
    redirect_to admin_root_path
  end
end

app/views/admin/show_times/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @show], html: {class: "form-admin"} do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :movie_id, t(".movie") %>
      <%= f.select :movie_id, Movie.pluck(:title, :id), {}, {class: "form-control"} %>
      <%= f.label :room_id, t(".room") %>
      <%= f.select :room_id, grouped_options_for_select(Cinema.grouped_options), {}, {class: "form-control"} %>
      <%= f.label :start_time, t(".start_time"), class: "margin-top-10" %>
      <%= f.datetime_field :start_time, class: "form-control" %>
      <%= f.label :price, t(".price") %>
      <%= f.number_field :price, class: "form-control" %>
      <%= f.submit t(".submit"), class: "button btn btn-primary" %>
    <% end %>
  </div>
</div>
<script>
    $('#show_time_movie_id').select2();
</script>

app/views/admin/show_times/_search.html.erb
<div class="overview-boxes">
  <div class="box-search">
    <div class="search-box">
      <%= search_form_for [:admin, @search], class: "input-group-form", method: "get" do |f| %>
      <div class="row justify-content-center width-100 padding-top-10">
        <div class="col-md-3 col-md-offset-3">
          <%= f.label :id_eq, t(".search_by_id") %>
          <%= f.text_field :id_eq, placeholder: t(".search_by_id_show"), class: "form-control title-input" %>
        </div>
        <div class="col-md-3 col-md-offset-3">
          <%= f.label :movie_title_eq, t(".search_by_movie") %>
          <%= f.select :movie_title_eq, Movie.all.pluck(:title), {:include_blank => true}, { class: "form-control title-input" } %>
        </div>
      </div>
        <div class="row justify-content-center width-100 padding-top-10">
        <div class="col-md-1 col-md-offset-3">
          <%= f.submit t(".search"), class: "btn btn-primary" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $('#q_movie_title_eq').select2({
      allowClear: true,
      placeholder: "Chọn tên một phim"
    });
</script>

app/views/admin/show_times/_show.html.erb
<tr>
  <th scope="row"><%= show.id %></th>
  <td><%= show.movie_title %></td>
  <td><%= show.room.cinema_name %></td>
  <td><%= show.room_name %></td>
  <td><%= l(show.start_time, format: :admin_show_time) %></td>
  <td><%= l(show.end_time, format: :admin_show_time) %></td>
  <td><%= number_to_currency show.price %></td>
  <td>
    <%= link_to edit_admin_show_time_path(show) do %>
      <span class="fa fa-pencil"></span>
    <% end %>
    <%= link_to admin_show_time_path(show), method: :delete,
          data: { confirm: t(".confirm")} do %>
      <span class="fa fa-trash"></span>
    <% end %>
  </td>
</tr>

app/views/admin/show_times/edit.html.erb
<% provide :title, t(".edit") %>

<div class="sales-boxes">
  <div class="admin-manager">
    <div class="title">
      <h1><%= t ".edit" %></h1>
    </div>
    <div class="admin-data">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/show_times/index.html.erb
<% provide :title, t(".show") %>
<%= render partial: "search"%>

<div class="sales-boxes">
  <div class="admin-manager box">
    <div class="title">
      <h1><%= t ".show" %></h1>
    </div>
    <%= link_to new_admin_show_time_path, class: "new-genre" do %>
      <span class="fa fa-plus-circle circle"></span>
      <%= t ".create" %>
    <% end %>
    <div class="admin-data">
      <table class="table table-categories table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col"><%= sort_link @search, :id, t(".id") %></th>
            <th scope="col"><%= sort_link @search, :movie_title, t(".movie") %></th>
            <th scope="col"><%= sort_link @search, :room_cinema_name, t(".cinema") %></th>
            <th scope="col"><%= sort_link @search, :room_name, t(".room") %></th>
            <th scope="col"><%= sort_link @search, :start_time, t(".start_time") %></th>
            <th scope="col"><%= sort_link @search, :end_time, t(".end_time") %></th>
            <th scope="col"><%= sort_link @search, :price, t(".price") %></th>
            <th scope="col"><%= t ".action" %></th>
          </tr>
        </thead>
        <tbody>
          <%= render partial: "show", collection: @shows %>
        </tbody>
      </table>
      <div id="pagy">
        <%== render partial: "shared/pagy", locals: { pagy: @pagy } %>
      </div>
    </div>
  </div>
</div>

app/views/admin/show_times/new.html.erb
<% provide :title, t(".create") %>

<div class="sales-boxes">
  <div class="admin-manager">
    <div class="title">
      <h1><%= t ".create" %></h1>
    </div>
    <div class="admin-data">
      <div class="container">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>