config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "/signup", to: "users#new"
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/activation", to: "payments#activation"
    get "/showing_movie", to: "specific_movies#showing_movie"
    get "/comming_movie", to: "specific_movies#comming_movie"
    resources :payments
    resources :searchs, only: :index
    resources :order_historys
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(show destroy index)
    resources :payment_activations, only: :edit
    resources :tickets
    resources :users
    resources :rates, only: :create
    resources :categories, only: :show
    resources :favorites, only: %i(index create destroy)
    resources :movies, only: %i(show) do
      resources :shows
    end

    resources :charts, only: [] do
      collection do
        get "top_movies_seller"
        get "top_movies_booking"
        get "revenue_by_day"
      end
    end

    namespace :admin do
      root "static_pages#home"
      get "/home", to: "static_pages#home"
      resources :movies
      resources :categories
      resources :show_times
      resources :cinemas
      resources :payments
      resources :users, only: %i(index show update)
    end
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < AdminController
  before_action :find_movie, only: %i(edit update destroy)

  def index
    @search = Movie.all.ransack(params[:q])
    @pagy, @movies = pagy @search.result,
                          items: Settings.model.limited
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new movie_params
    if @movie.save
      flash[:success] = t "movie_create"
      redirect_to admin_movies_path
    else
      flash[:danger] = t "movie_create_failed"
      render :new
    end
  end

  def edit; end

  def update
    if params.dig(:movie, :status_before_type_cast)
      update_active
    else
      update_all
    end
  end

  def destroy
    if @movie.shows.any?
      flash[:danger] = t "movie_delete_denied"
    elsif @movie.destroy
      flash[:success] = t "movie_delete"
    else
      flash[:danger] = t "movie_delete_failed"
    end
    redirect_to admin_movies_path
  end

  private
  def movie_params
    params.require(:movie).permit(Movie::MOVIE_ATTRS, :image, :banner, category_ids: [],
      movie_categories_attributes:
          [:id, :movie_id, :category_id])
  end

  def update_active
    if params.dig(:movie, :status_before_type_cast) == "0"
      if @movie.show_times.not_out_of_date.size == 0
        if @movie.update_column(:status,
                                params.dig(:movie, :status_before_type_cast))
          flash[:success] = t("movie_update")
        else
          flash[:danger] = t("movie_update_failed")
        end
      else
        flash[:danger] = t("movie_update_denied")
      end
    else
      if @movie.update_column(:status, params.dig(:movie, :status_before_type_cast))
        flash[:success] = t("movie_update")
      else
        flash[:danger] = t("movie_update_failed")
      end
    end
    redirect_to admin_movies_path
  end

  def update_all
    if @movie.update movie_params
      flash[:success] = t("movie_update")
      redirect_to admin_movies_path
    else
      flash[:danger] = t("movie_update_failed")
      render :edit
    end
  end

  def find_movie
    @movie = Movie.find_by id: params[:id]
    return if @movie

    flash[:danger] = t "not_found"
    redirect_to admin_root_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: :show
  before_action :related_movie

  def show
    @pagy, @rates = pagy @movie.rates.latest,
                           items: Settings.page.comment
  end

  private

  def find_movie
    @movie = Movie.find_by id: params[:id]
    return if @movie

    flash[:warning] = t ".not_found"
    redirect_to root_path
  end

  def related_movie
    @categories_ids = @movie.categories&.pluck :id
    @related_movie = Movie.active.joins(:categories).where('categories.id IN (?)', @categories_ids).limit(5)
  end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
  def movie_ticket_revenue movie
    total = 0
    movie.tickets.each{|ticket| total += ticket.show_time_price}
    total
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def showing? movie
    movie.release_time <= Time.zone.now
  end

  def sort_value
    if @search && @search.sorts.present?
      [@search.sorts.first.name, @search.sorts.first.dir].join(' ')
    end
  end

  def movie_revenue movie
    total = 0
    movie.tickets.each{|ticket| total += ticket.show_time_price}
    total
  end
end

app/views/movies/_add_favorite.html.erb
<%= link_to favorites_path(id: params[:id]), method: :post, class: "follow-btn", remote: true do %>
  <i class="fa-regular fa-heart" style="color: #ffffff;"></i> <%= t ".favorite" %>
<% end %>

app/views/movies/_break_movie.html.erb
<div class="product__item">
  <div class="product__item__pic set-bg" data-setbg="img/popular/popular-1.jpg">
    <div class="ep">18 / 18</div>
    <div class="comment"><i class="fa fa-comments"></i> 11</div>
    <div class="view"><i class="fa fa-eye"></i> 9141</div>
  </div>
  <div class="product__item__text">
    <ul>
      <li>Active</li>
      <li>Movie</li>
    </ul>
    <h5><a href="#">Sen to Chihiro no Kamikakushi</a></h5>
  </div>
</div>

app/views/movies/_favorites_button.html.erb
<span id="favorite_button">
  <% if logged_in? %>
    <%= favorited(current_user, params[:id]) ? render("remove_favorite") : render("add_favorite") %>
  <% else %>
    <%= render("add_favorite") %>
  <% end %>
</span>

app/views/movies/_hot_movie.html.erb
<div class="hot-movie">
  <% if movie.image %>
    <div class="product__sidebar__view__item set-bg mix day years" data-setbg=<%= url_for movie.image_url %>>
    <% else %>
      <div class="product__sidebar__view__item set-bg mix day years" data-setbg=<%= movie.img_link %>>
      <% end %>
      <div class="ep"><%= movie.age_range %>+</div>
      <div class="view" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng suất chiếu"><i class="fa fa-eye"></i> <%= movie.show_times.size %></div>
    </div>
    <h5 class="title-movie"><%= link_to movie.title, movie_path(id: movie.id)%></h5>
</div>

app/views/movies/_movie.html.erb
<div class="col-lg-3 col-md-4 col-sm-4">
  <div class="product__item">
    <% if movie.image %>
      <div class="product__item__pic height-400 set-bg"  data-setbg=<%= url_for movie.image_url %>>
    <% else %>
      <div class="product__item__pic height-400 set-bg" data-setbg=<%= movie.img_link %>>
    <% end %>
      <div class="ep"><%= movie.age_range %>+</div>
      <div class="comment" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng đánh giá"><i class="fa fa-comments"></i> <%= movie.rates.size %></div>
      <div class="view" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng suất chiếu" ><i class="fa fa-eye"></i> <%= movie.show_times.size %></div>
    </div>
    <div class="product__item__text">
      <ul>
       <% movie.categories&.pluck(:name).each do |categories_name|%>
        <li><%= categories_name %></li>
        <% end %>
      </ul>
      <h5><%= link_to movie.title, movie_path(id: movie.id) %></h5>
    </div>
  </div>
</div>

app/views/movies/_movie_index.html.erb
<div class="col-lg-4 col-md-6 col-sm-6">
  <div class="product__item">
    <% if movie.image %>
      <div class="product__item__pic set-bg"  data-setbg=<%= url_for movie.image_url %>>
    <% else %>
      <div class="product__item__pic set-bg" data-setbg=<%= movie.img_link %>>
    <% end %>
      <div class="ep"><%= movie.age_range %>+ </div>
      <div class="comment" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng đánh giá"><i class="fa fa-comments"></i> <%= movie.rates.size %></div>
      <div class="view" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng suất chiếu"><i class="fa fa-eye"></i> <%= movie.show_times.size %></div>
    </div>
    <div class="product__item__text">
      <ul>
        <% movie.categories&.pluck(:name).each do |categories_name|%>
        <li><%= categories_name %></li>
        <% end %>
      </ul>
      <h5><%= link_to movie.title, movie_path(id: movie.id) %></h5>
    </div>
  </div>
</div>

app/views/movies/_remove_favorite.html.erb
<%= link_to favorite_path(favorited(current_user, params[:id]).id), method: :delete, class: "follow-btn", remote: true do %>
  <i class="fa-solid fa-heart" style="color: #ffffff;"></i> <%= t ".unfavorite" %>
<% end %>

app/views/movies/show.html.erb
<% provide :title, t(".details") %>
<div class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__links">
          <%= link_to root_path do %>
            <i class="fa fa-home"></i><%= t ".home" %>
          <% end %>
          <span><%= @movie.title %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="anime-details spad">
  <div class="container">
    <div class="anime__details__content">
      <div class="row">
        <div class="col-lg-3">
          <% if @movie.image %>
            <div class="anime__details__pic set-bg" data-setbg=<%= url_for @movie.image_url %>>
              <div class="comment" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng đánh giá"><i class="fa fa-comments"></i> <%= @movie.rates.size %></div>
              <div class="view" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng suất chiếu"><i class="fa fa-eye"></i> <%= @movie.show_times.size %></div>
            </div>
          <% else %>
            <div class="anime__details__pic set-bg" data-setbg=<%= @movie.img_link %>>
              <div class="comment" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng đánh giá"><i class="fa fa-comments"></i> <%= @movie.rates.size %></div>
              <div class="view" data-bs-toggle="tooltip" data-bs-placement="top" title="Số lượng suất chiếu"><i class="fa fa-eye"></i> <%= @movie.show_times.size %></div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-9">
          <div class="anime__details__text">
            <div class="anime__details__title">
              <h3><%= @movie.title %></h3>
              <%# <span>フェイト／ステイナイト, Feito／sutei naito</span> %>
            </div>
            <div class="anime__details__rating">
              <div class="rating">
                <a href="#"><i class="fa-solid fa-star" style="color: #ffdd00;"></i></a>
                <a href="#"><i class="fa-solid fa-star" style="color: #ffdd00;"></i></a>
                <a href="#"><i class="fa-solid fa-star" style="color: #ffdd00;"></i></a>
                <a href="#"><i class="fa-solid fa-star" style="color: #ffdd00;"></i></a>
                <a href="#"><i class="fa-solid fa-star-half-stroke" style="color: #ffdd00;"></i></a>
              </div>
              <span></span>
            </div>
            <p><%= @movie.description %></p>
            <div class="anime__details__widget">
              <div class="row">
                <div class="col-lg-6 col-md-6">
                  <ul>
                    <li><span class="width-135"><%= t ".release" %></span><%= l(@movie.release_time, format: :default) %></li>
                    <li><span class="width-135"><%= t ".director" %></span><%= @movie.director %></li>
                    <li><span class="width-135"><%= t ".cast" %></span><%= @movie.cast %></li>
                    <li><span class="width-135"><%= t ".categories" %></span><%= @movie.categories&.pluck(:name).join(", ") %></li>
                  </ul>
                </div>
                <div class="col-lg-6 col-md-6">
                  <ul>
                    <li><span class="width-135"><%= t ".language" %></span><%= @movie.language %></li>
                    <li><span class="width-135"><%= t ".age_range" %></span><%= @movie.age_range %></li>
                    <li><span class="width-135"><%= t ".duration" %></span><%= @movie.duration_min %>&nbsp;<%= t ".min" %></li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="anime__details__btn">
              <%= render "favorites_button" %>
              <% if showing? @movie %>
                <%= link_to movie_shows_path(@movie), class: "watch-btn" do %>
                  <span><%= t ".booking" %></span>
                  <i class="fa-solid fa-chevron-right" style="color: #ffffff;"></i>
                <% end %>
              <% else %>
                <a class="watch-btn ban"><span><%= t ".comming" %></span> <i class="fa-solid fa-chevron-right" style="color: #ffffff;"></i></a>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-8 col-md-8">
        <div class="anime__details__review">
          <div class="section-title">
            <h5><%= t ".reviews" %></h5>
          </div>
          <div id="comments_list">
            <%= render @rates %>
          </div>
          <% if @rates.present? %>
            <div id="pagy">
              <%== render partial: "shared/pagy", locals: { pagy: @pagy } %>
            </div>
          <% end %>
          <div class="anime__details__form">
            <div class="section-title">
              <h5><%= t ".comments" %></h5>
            </div>
            <%= form_for(:rate, url: rates_path, remote: true) do |f| %>
              <div id="comment-error"></div>
              <div class="input__item">
                <%= f.text_area :comment, placeholder: t(".comments") %>
                <%= hidden_field_tag :movie_id, @movie.id %>
              </div>
              <button type="submit"><i class="fa fa-location-arrow"></i> <%= t ".review" %></button>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4">
        <div class="anime__details__sidebar">
          <div class="section-title">
            <h5><%= t ".might_like" %></h5>
          </div>
          <%= render partial: "movies/hot_movie", collection: @related_movie, as: :movie %>
        </div>
      </div>
    </div>
  </div>
</section>