config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "/signup", to: "users#new"
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/activation", to: "payments#activation"
    get "/showing_movie", to: "specific_movies#showing_movie"
    get "/comming_movie", to: "specific_movies#comming_movie"
    resources :payments
    resources :searchs, only: :index
    resources :order_historys
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(show destroy index)
    resources :payment_activations, only: :edit
    resources :tickets
    resources :users
    resources :rates, only: :create
    resources :categories, only: :show
    resources :favorites, only: %i(index create destroy)
    resources :movies, only: %i(show) do
      resources :shows
    end

    resources :charts, only: [] do
      collection do
        get "top_movies_seller"
        get "top_movies_booking"
        get "revenue_by_day"
      end
    end

    namespace :admin do
      root "static_pages#home"
      get "/home", to: "static_pages#home"
      resources :movies
      resources :categories
      resources :show_times
      resources :cinemas
      resources :payments
      resources :users, only: %i(index show update)
    end
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/layouts/admin/_sidebar.html.erb
<div class="sidebar">
  <div class="logo-details">
    <i class='bx bxs-camera-movie' ></i>
    <span class="logo_name">Admin page</span>
  </div>
  <ul class="nav-links">
    <li>
      <%= link_to admin_root_path, class: "active" do %>
        <i class='bx bx-grid-alt' ></i>
        <span class="links_name"><%= t ".dashboard" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_categories_path, class: "nav_link" do %>
        <i class='bx bxs-category-alt'></i>
        <span class="links_name"><%= t ".genres" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_movies_path, class: "nav_link" do %>
        <i class='bx bxs-movie-play' ></i>
        <span class="links_name"><%= t ".movies" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_show_times_path, class: "nav_link" do %>
        <i class='bx bxs-slideshow'></i>
        <span class="links_name"><%= t ".shows" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_cinemas_path, class: "nav_link" do %>
        <i class='bx bxs-building-house' ></i>
        <span class="links_name"><%= t ".cinemas" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_payments_path, class: "nav_link" do %>
        <i class='bx bx-pie-chart-alt-2' ></i>
        <span class="links_name"><%= t ".payments" %></span>
      <% end %>
    </li>
    <li>
      <%= link_to admin_users_path, class: "nav_link" do %>
        <i class='bx bxs-user-account'></i>
        <span class="links_name"><%= t ".users" %></span>
      <% end %>
    </li>
    <li class="log_out">
      <%= link_to logout_path, method: :delete do %>
        <i class='bx bx-log-out'></i>
        <span class="links_name"><%= t(".log_out")%></span>
      <% end %>
    </li>
  </ul>
</div>