config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "/signup", to: "users#new"
    root "static_pages#home"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/activation", to: "payments#activation"
    get "/showing_movie", to: "specific_movies#showing_movie"
    get "/comming_movie", to: "specific_movies#comming_movie"
    resources :payments
    resources :searchs, only: :index
    resources :order_historys
    resources :account_activations, only: :edit
    resources :password_resets, except: %i(show destroy index)
    resources :payment_activations, only: :edit
    resources :tickets
    resources :users
    resources :rates, only: :create
    resources :categories, only: :show
    resources :favorites, only: %i(index create destroy)
    resources :movies, only: %i(show) do
      resources :shows
    end

    resources :charts, only: [] do
      collection do
        get "top_movies_seller"
        get "top_movies_booking"
        get "revenue_by_day"
      end
    end

    namespace :admin do
      root "static_pages#home"
      get "/home", to: "static_pages#home"
      resources :movies
      resources :categories
      resources :show_times
      resources :cinemas
      resources :payments
      resources :users, only: %i(index show update)
    end
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :find_movie
  before_action :logged_in_user, :store_show_time_url, only: :show

  def index
    @filter_showtime = ShowTime.ransack({filter_date: [params[:movie_id], params[:start_time] || Time.now]})
    @show_times = @filter_showtime.result.group_by(&:room_id)
    @cinemas = Cinema.all

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    unless check_payment? ||current_payment&.payment_expired? || current_payment&.active?
      delete_payment
      @payment = Payment.create user_id: current_user.id
      init_payment @payment
    end
    @show = ShowTime.find_by id: params[:id]
    @room = @show.room
  end

  private

  def find_movie
    @movie = Movie.find_by id: params[:movie_id]
    return if @movie

    flash[:warning] = t ".not_found"
    redirect_to root_path
  end
end

app/views/shows/_show_time_for_cinema.html.erb
<% show_times.each do |rooms_id, showtime_list| %>
  <%= cinema.rooms.ids.include?(rooms_id) ? render(partial: "showtimes/show_time", collection: showtime_list, as: :show) : "" %>
<% end %>

app/views/shows/index.html.erb
<div class="breadcrumb-option">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb__links">
          <%= link_to root_path do %>
            <i class="fa fa-home"></i><%= t ".home" %>
          <% end %>
          <span><%= link_to @movie.title, movie_path(@movie.id) %></span>
          <span><%= t ".show_time" %></span>
        </div>
      </div>
    </div>
  </div>
</div>
<section class="blog-details spad">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8 search-date-form">
        <div class="blog__details__title">
          <%= form_tag(movie_shows_path(id: params[:movie_id]), class: "row d-flex justify-content-center", method: :get, remote: true) do |f| %>
            <%= hidden_field_tag :movie_id, @movie.id %>
            <div class="col-md-9">
              <%= date_field_tag :start_time, params[:start_time] || l(Time.now, format: :search) , class:"form-control", min: l(Time.now, format: :search) %>
            </div>
            <div class="col col-lg-3">
              <button type="submit" class="btn btn-danger w-100">
                <i class="fas fa-search search-book"></i>
                <span><%= t ".search" %></span>
              </button>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="blog__details__content">
          <div class="blog__details__comment">
            <h4><%= t ".shows_list" %></h4>
            <div class="blog__details__comment__item">
              <div class="blog__details__comment__item__text">
                <div class="detail-group-cinema">
                  <%= render partial: "cinemas/cinema", locals: {cinemas: @cinemas, show_times: @show_times, date: params[:start_time]&.to_datetime || Time.now } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shows/index.js.erb
$('#list-show-time').html("<%= j render partial: "cinemas/cinema", locals:{cinemas: @cinemas, show_times: @show_times, date: params[:start_time]&.to_date || Time.now} %>")

app/views/shows/show.html.erb
<section class="anime-details spad padding-top-30">
  <div class="container">
    <div class="anime__details__episodes">
      <div class="section-title">
        <h5><%= t ".seats_list" %></h5>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9">
        <div class="anime__details__episodes">
          <div class="anime__video__player margin-bottom-20">
            <%= image_tag "bg.jpg" %>
          </div>
          <div class="screen"><%= t ".screen" %></div>
          <div class="seat-cinema">
            <span class="seat-cinema-selected"><%= t ".seat_selected" %></span>
            <span class="seat-cinema-unavailable"><%= t ".seat_unavailable" %></span>
            <span class="seat-cinema-normal"><%= t ".seat_normal" %></span>
          </div>
          <div style="padding-left: 35px;">
            <% @room.row.times do |i| %>
              <% seat_letter = Settings.seat_code.seat_letter[i] %>
              <ul class="seat-row">
                <li class="seat-label"><%= seat_letter %></li>
                <li>
                  <ul class="seat-col">
                    <% index = 1 %>
                    <% @room.length.times do %>
                      <% seat_position =  seat_letter + index.to_s %>
                      <span id=<%= "#{seat_position}"%> >
                        <% if is_booking? @show.id, seat_position %>
                          <li>
                            <%= link_to index, ticket_path(show_time_id: @show.id, seat_position: seat_position, payment_id: session[:payment_id], index: index, seat_letter: seat_letter), remote: true, method: :delete, class: "choosen" %>
                          </li>
                        <% elsif was_taken? @show.id, seat_position %>
                          <li><a class="taken"><%= index %></a></li>
                        <% else %>
                          <li>
                            <%= link_to index, tickets_path(show_time_id: @show.id, seat_position: seat_position, payment_id: session[:payment_id], index: index), remote: true, method: :post %>
                          </li>
                        <%end%>
                      </span>
                      <% index += 1 %>
                    <% end %>
                  </ul>
                </li>
                <li class="seat-label"><%= seat_letter %></li>
              </ul>
            <% end %>
          </div>
        </div>
        <div class="row d-flex justify-content-center">
          <%= link_to payment_path(current_payment), class: "watch-btn" do %>
            <span><%= t ".going" %></span> <i class="fa fa-angle-right"></i>
          <% end %>
        </div>
      </div>
      <div class="col-md-3">
        <div>
          <section>
            <article class="row">
              <div class="col-md-12 image-div" style="margin-bottom: 15px;">
                <% if @movie.image %>
                  <%= image_tag @movie.image_url %>
                <% else %>
                  <%= image_tag @movie.img_link %>
                <% end %>
              </div>
              <div class="col-md-12">
                <div class="ticket-detail">
                  <h2 class="ticket-title vn upper-text"><%= @movie.title %></h2>
                  <h2 class="ticket-title upper-text"><%= @movie.title %></h2>
                  <div class="ticket-icon"></i><span class="notice"> <%= t ".movie_range" %> <%= @movie.age_range %> <%= t ".age_notice" %></span></div>
                <div class="ticket-info">
                  <div class="dotted-line"><b><%= t ".cinema" %>: &nbsp;</b><%=  @room.cinema.name %></div>
                  <div class="dotted-line"><b><%= t ".room" %>: &nbsp;</b><%= @room.name %></div>
                  <div class="dotted-line"><b><%= t ".time" %>: &nbsp;</b><%=@show.start_time.to_fs(:time) %></div>
                  <div class="dotted-line"><b><%= t ".date" %>: &nbsp;</b><%= l(@show.start_time, format: :weekday)%></div>
                  <div class="dotted-line">
                    <b><%= t ".seat" %>: &nbsp;</b>
                    <span id="select-seat"><%= payment_seat_position @show.id %></span>
                  </div>
                </div>
                <div class="ticket-price-total">
                  <p>
                    <%= t ".sum" %>: &nbsp;
                    <span id="price-booking"><%= number_to_currency(sum_price_show(@show.id)) %></span>
                  </p>
                </div>
              </div>
            </div>
          </article>
        </section>
      </div>
    </div>
  </div>
</section>